import type { CellRow, PipelineStage, MetricCard } from "@/shared/types"

export const hqMetrics: MetricCard[] = [
  {
    label: "ACTIVE CELLS",
    value: "5",
    sub: "↑ 5 UK regions",
    subPositive: true,
  },
  {
    label: "TOTAL CASES",
    value: "1,947",
    sub: "↑ 12% MoM",
    subPositive: true,
  },
  {
    label: "GROSS RECOVERY",
    value: "£2.63M",
    sub: "↑ £340K this month",
    subPositive: true,
  },
  {
    label: "COMPLIANCE SCORE",
    value: "89%",
    sub: "↓ 2 flags open",
    subNegative: true,
  },
]

export const hqPipeline: PipelineStage[] = [
  { key: "intake", label: "INTAKE", count: 286 },
  { key: "letter_of_claim", label: "LETTER OF CLAIM", count: 394 },
  {
    key: "awaiting_response",
    label: "AWAITING RESPONSE",
    count: 142,
    highlighted: true,
  },
  { key: "negotiation", label: "NEGOTIATION", count: 478 },
  { key: "settlement", label: "SETTLEMENT", count: 261 },
  { key: "closed", label: "CLOSED", count: 386 },
  { key: "blocked", label: "BLOCKED", count: 24, blocked: true },
]

export const hqCells: CellRow[] = [
  {
    id: "cell-001",
    name: "Housing · Manchester",
    subtitle: "Housing disrepair",
    location: "Manchester, UK",
    clioId: "CLIO-MCR-HSG-001",
    status: "Active",
    cases: 412,
    recovery: "£586K",
    avgCycle: "71 days",
    docCompliance: 93,
    flags: null,
  },
  {
    id: "cell-002",
    name: "PCP · Birmingham",
    subtitle: "PCP mis-selling claims",
    location: "Birmingham, UK",
    clioId: "CLIO-BHM-PCP-002",
    status: "At Risk",
    cases: 624,
    recovery: "£842K",
    avgCycle: "86 days",
    docCompliance: 86,
    flags: "12 LOC overdue",
  },
  {
    id: "cell-003",
    name: "Data · London",
    subtitle: "Data protection & GDPR breach",
    location: "London, UK",
    clioId: "CLIO-LON-DPR-003",
    status: "Active",
    cases: 238,
    recovery: "£312K",
    avgCycle: "54 days",
    docCompliance: 96,
    flags: null,
  },
  {
    id: "cell-004",
    name: "Employment · Leeds",
    subtitle: "Unfair dismissal & discrimination",
    location: "Leeds, UK",
    clioId: "CLIO-LDS-EMP-004",
    status: "Critical",
    cases: 184,
    recovery: "£221K",
    avgCycle: "92 days",
    docCompliance: 78,
    flags: "SRA query open",
  },
  {
    id: "cell-005",
    name: "RTA · Glasgow",
    subtitle: "Road traffic accident PI",
    location: "Glasgow, UK",
    clioId: "CLIO-GLA-RTA-005",
    status: "Active",
    cases: 489,
    recovery: "£674K",
    avgCycle: "68 days",
    docCompliance: 92,
    flags: null,
  },
]
